import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: "#e8efff",
	},
	scrollContent: {
		paddingHorizontal: 20,
		paddingTop: 24,
		paddingBottom: 40,
		gap: 20,
	},
	heroCard: {
		backgroundColor: "#0f172a",
		borderRadius: 28,
		padding: 24,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 16 },
		shadowOpacity: 0.15,
		shadowRadius: 24,
		elevation: 8,
		gap: 12,
	},
	heroBadge: {
		alignSelf: "flex-start",
		backgroundColor: "rgba(255,255,255,0.12)",
		borderRadius: 999,
		paddingHorizontal: 14,
		paddingVertical: 6,
		color: "#c7d2fe",
		fontSize: 12,
		fontWeight: "700",
		textTransform: "uppercase",
	},
	heroTitle: {
		fontSize: 26,
		fontWeight: "800",
		color: "#ffffff",
		lineHeight: 32,
	},
	heroSubtitle: {
		fontSize: 15,
		color: "#cbd5f5",
	},
	summaryCard: {
		backgroundColor: "#ffffff",
		borderRadius: 26,
		padding: 24,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 12 },
		shadowOpacity: 0.08,
		shadowRadius: 18,
		elevation: 6,
		gap: 16,
	},
	summaryHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	sectionLabel: {
		fontSize: 13,
		color: "#94a3b8",
		fontWeight: "700",
		textTransform: "uppercase",
		letterSpacing: 0.8,
		marginBottom: 6,
	},
	summaryGreeting: {
		fontSize: 18,
		fontWeight: "700",
		color: "#0f172a",
	},
	modeBadge: {
		backgroundColor: "#dbeafe",
		borderRadius: 999,
		paddingHorizontal: 14,
		paddingVertical: 6,
	},
	modeBadgeText: {
		fontSize: 13,
		fontWeight: "700",
		color: "#1d4ed8",
	},
	summaryGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 12,
	},
	summaryStat: {
		flexGrow: 1,
		minWidth: "45%",
		backgroundColor: "#f8fafc",
		borderRadius: 18,
		paddingVertical: 16,
		paddingHorizontal: 18,
	},
	summaryStatLabel: {
		fontSize: 13,
		color: "#475569",
		marginBottom: 6,
	},
	summaryStatValue: {
		fontSize: 20,
		fontWeight: "800",
		color: "#0f172a",
	},
	summaryFooter: {
		borderTopWidth: 1,
		borderTopColor: "#e2e8f0",
		paddingTop: 12,
	},
	summaryFooterLabel: {
		fontSize: 13,
		color: "#94a3b8",
		marginBottom: 4,
	},
	summaryFooterValue: {
		fontSize: 15,
		color: "#0f172a",
		fontWeight: "600",
	},
	favoriteCard: {
		backgroundColor: "#ffffff",
		borderRadius: 26,
		padding: 20,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.08,
		shadowRadius: 16,
		elevation: 6,
		gap: 12,
	},
	favoritesHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	favoritesSubtitle: {
		fontSize: 14,
		color: "#475569",
		marginTop: 4,
	},
	favoritesCount: {
		fontSize: 24,
		fontWeight: "800",
		color: "#1d4ed8",
	},
	favoriteList: {
		marginTop: 8,
	},
	favoriteListContent: {
		paddingBottom: 4,
	},
	favoriteItem: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 12,
	},
	favoriteItemText: {
		flex: 1,
		paddingRight: 12,
	},
	favoriteWord: {
		fontSize: 16,
		fontWeight: "700",
		color: "#0f172a",
		marginBottom: 4,
	},
	favoritePhonetic: {
		fontSize: 13,
		color: "#475569",
		marginBottom: 4,
	},
	favoriteDefinition: {
		fontSize: 14,
		color: "#334155",
	},
	favoriteActions: {
		flexDirection: "row",
		alignItems: "center",
		columnGap: 8,
	},
	favoriteActionButton: {
		width: 40,
		height: 40,
		borderRadius: 12,
		backgroundColor: "#eef2ff",
		alignItems: "center",
		justifyContent: "center",
	},
	favoriteSeparator: {
		height: 1,
		backgroundColor: "#e2e8f0",
	},
	emptyFavoriteText: {
		fontSize: 15,
		color: "#94a3b8",
		textAlign: "center",
		paddingVertical: 24,
	},
});
