import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: "#e8efff",
	},
	scrollContent: {
		paddingHorizontal: 20,
		paddingTop: 24,
		paddingBottom: 40,
		gap: 20,
	},
	heroCard: {
		backgroundColor: "#0f172a",
		borderRadius: 28,
		padding: 24,
		gap: 8,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 16 },
		shadowOpacity: 0.15,
		shadowRadius: 24,
		elevation: 8,
	},
	heroTitle: {
		fontSize: 26,
		fontWeight: "800",
		color: "#ffffff",
	},
	heroSubtitle: {
		fontSize: 15,
		color: "#cbd5f5",
	},
	helpCard: {
		backgroundColor: "#ffffff",
		borderRadius: 24,
		padding: 20,
		gap: 8,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.08,
		shadowRadius: 16,
		elevation: 6,
	},
	helpTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#0f172a",
	},
	helpDescription: {
		fontSize: 14,
		color: "#475569",
		lineHeight: 20,
	},
	versionCard: {
		backgroundColor: "#ffffff",
		borderRadius: 24,
		padding: 20,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.08,
		shadowRadius: 16,
		elevation: 6,
	},
	versionLabel: {
		fontSize: 14,
		color: "#475569",
	},
	versionValue: {
		fontSize: 18,
		fontWeight: "800",
		color: "#0f172a",
	},
	authenticatedActionsContainer: {
		gap: 16,
	},
	profileButton: {
		backgroundColor: "#1d4ed8",
		borderRadius: 24,
		padding: 20,
		gap: 6,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 12 },
		shadowOpacity: 0.12,
		shadowRadius: 18,
		elevation: 6,
	},
	profileButtonTitle: {
		fontSize: 20,
		fontWeight: "800",
		color: "#ffffff",
	},
	profileButtonDescription: {
		fontSize: 14,
		color: "#dbeafe",
		lineHeight: 20,
	},
	accountActions: {
		gap: 12,
	},
	homeButton: {
		backgroundColor: "#0f172a",
		borderRadius: 18,
		paddingVertical: 14,
		alignItems: "center",
	},
	homeButtonText: {
		color: "#ffffff",
		fontSize: 16,
		fontWeight: "700",
	},
	logoutButton: {
		backgroundColor: "#ef4444",
		borderRadius: 18,
		paddingVertical: 14,
		alignItems: "center",
	},
	logoutButtonText: {
		color: "#ffffff",
		fontSize: 16,
		fontWeight: "700",
	},
	guestCard: {
		backgroundColor: "#ffffff",
		borderRadius: 24,
		padding: 24,
		gap: 16,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.08,
		shadowRadius: 16,
		elevation: 6,
	},
	guestTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#0f172a",
	},
	guestDescription: {
		fontSize: 14,
		color: "#475569",
		lineHeight: 20,
	},
	primaryCta: {
		backgroundColor: "#1d4ed8",
		borderRadius: 18,
		paddingVertical: 14,
		alignItems: "center",
	},
	primaryCtaText: {
		color: "#ffffff",
		fontSize: 16,
		fontWeight: "700",
	},
	secondaryCta: {
		borderWidth: 1,
		borderColor: "#dbeafe",
		borderRadius: 18,
		paddingVertical: 14,
		alignItems: "center",
	},
	secondaryCtaText: {
		color: "#1d4ed8",
		fontSize: 16,
		fontWeight: "700",
	},
});
